version: '3'

services:
  slb-haproxy:
    image: tomammon/tomammon.net:haproxy-slb
    restart: always
    container_name: slb-haproxy
    ports:
      - 80:80
      - 1936:1936
    volumes:
      - /opt/tan/slb-haproxyconfig/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      default:
      backend:
        ipv4_address: 192.168.0.2

  websrv-a:
    image: alastairhm/alpine-lighttpd-php
    restart: always
    container_name: websrv-a
    volumes:
      - /opt/tan/appcode/websrv:/var/www
    networks:
      backend:
        ipv4_address: 192.168.0.10

  websrv-b:
    image: alastairhm/alpine-lighttpd-php
    restart: always
    container_name: websrv-b
    volumes:
      - /opt/tan/appcode/websrv:/var/www
    networks:
      backend:
        ipv4_address: 192.168.0.11

  appsrv-a:
    image: tomammon/tomammon.net:appserver
    restart: always
    container_name: appsrv-a
    volumes:
      - /opt/tan/appcode/appsrv:/var/www/html
    networks:
      backend:
        ipv4_address: 192.168.0.100

  appsrv-b:
    image: tomammon/tomammon.net:appserver
    restart: always
    container_name: appsrv-b
    volumes:
      - /opt/tan/appcode/appsrv:/var/www/html
    networks:
      backend:
        ipv4_address: 192.168.0.101

  database:
    image: mariadb:10.0.33
    restart: always
    container_name: tandb_slave
    environment:
      MYSQL_ROOT_PASSWORD: ${TANDB_PASSWD}
    volumes:
      - /opt/tan/dbdata:/var/lib/mysql
      - /opt/tan/dbconfig:/etc/mysql/conf.d
    networks:
      default:
      backend:
        ipv4_address: 192.168.0.200


networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24  
